EDAC, mce_amd_inj: Make it depend on AMD_NB
... now that it uses its facilities.

It, too, takes care of randconfig splats like this one:

drivers/edac/mce_amd_inj.c: In function ‘toggle_nb_mca_mst_cpu’:
drivers/edac/mce_amd_inj.c:218:42: warning: dereferencing ‘void *’ pointer [enabled by default]
  struct pci_dev *F3 = node_to_amd_nb(nid)->misc;
                                          ^
drivers/edac/mce_amd_inj.c:218:42: error: request for member ‘misc’ in something not a structure or union
make[2]: *** [drivers/edac/mce_amd_inj.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [drivers/edac] Error 2

Signed-off-by: Borislav Petkov <bp@suse.de>
Cc: Aravind Gopalakrishnan <Aravind.Gopalakrishnan@amd.com>