drivers/gpu/drm/i915/intel_sprite.c: fix build
gcc-4.4.4:

cc1: warnings being treated as errors
drivers/gpu/drm/i915/intel_sprite.c: In function 'intel_check_sprite_plane':
drivers/gpu/drm/i915/intel_sprite.c:767: error: 'src_x' may be used uninitialized in this function
drivers/gpu/drm/i915/intel_sprite.c:767: error: 'src_y' may be used uninitialized in this function
drivers/gpu/drm/i915/intel_sprite.c:767: error: 'src_w' may be used uninitialized in this function
drivers/gpu/drm/i915/intel_sprite.c:767: error: 'src_h' may be used uninitialized in this function

Fixes: 96d61a7f267f ("drm/i915: split intel_update_plane into check() and commit()")
Cc: Gustavo Padovan <gustavo.padovan@collabora.co.uk>
Cc: Ville Syrjala <ville.syrjala@linux.intel.com>
Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>