phy: cadence-torrent: initialize pcie_links variable
When we use clang to build with -Wall and -Werror flags we can see
this issue:

drivers/phy/cadence/phy-cadence-torrent.c:2493:5: error: variable
'pcie_links' is uninitialized when used here [-Werror,-Wuninitialized]
                                pcie_links++;
                                ^~~~~~~~~~

pcie_links variable is now initialized to fix this.

Fixes: d0d3c1e91c7a ("phy: cadence-torrent: Add PCIe multilink + USB with same SSC register config for 100MHz refclk")
Signed-off-by: Julien Masson <jmasson@baylibre.com>