mm: fix up new locking syscalls
Extend the arm64 compat syscall table for the new syscalls to fix build
errors introduced by "mm: mlock: add new mlock, munlock, and munlockall
system calls":

 ../arch/arm64/include/asm/unistd32.h:801:1: error: array index in initializer exceeds array bounds
 ../arch/arm64/include/asm/unistd32.h:801:1: error: (near initialization for 'compat_sys_call_table')
 ../arch/arm64/include/asm/unistd32.h:803:1: error: array index in initializer exceeds array bounds
 ../arch/arm64/include/asm/unistd32.h:803:1: error: (near initialization for 'compat_sys_call_table')
 ../arch/arm64/include/asm/unistd32.h:805:1: error: array index in initializer exceeds array bounds
 ../arch/arm64/include/asm/unistd32.h:805:1: error: (near initialization for 'compat_sys_call_table')

Signed-off-by: Mark Brown <broonie@kernel.org>
Cc: Eric B Munson <emunson@akamai.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>