PENDING: dmaengine: ti: k3-udma-common: Fix errors with CONFIG_TI_K3_UDMA=n
Fix following Linker errors when TI_K3_UDMA driver is disabled:

aarch64-none-linux-gnu-ld: Unexpected GOT/PLT entries detected!
aarch64-none-linux-gnu-ld: Unexpected run-time procedure linkages detected!
aarch64-none-linux-gnu-ld: drivers/dma/ti/k3-udma-common.o: in function `xudma_navss_psil_unpair':
drivers/dma/ti/k3-udma-private.c:21:(.text+0x31c): undefined reference to `navss_psil_unpair'
aarch64-none-linux-gnu-ld: drivers/dma/ti/k3-udma-common.o: in function `xudma_navss_psil_pair':
drivers/dma/ti/k3-udma-private.c:15:(.text+0x338): undefined reference to `navss_psil_pair'
aarch64-none-linux-gnu-ld: drivers/dma/ti/k3-udma-common.o: in function `udma_free_chan_resources':
drivers/dma/ti/k3-udma-common.c:2071:(.text+0x4054): undefined reference to `navss_psil_unpair'

Signed-off-by: Sai Sree Kartheek Adivi <s-adivi@ti.com>
(cherry picked from commit 5e22e73c0638c675d7c65661733bafcabf3cdbc3)
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>