drm/exynos: fix compile error and warning of g2d
Should be !g2d_userptr->vec, not !vec. This will fix below compile
error.

drivers/gpu/drm/exynos/exynos_drm_g2d.c: In function ‘g2d_userptr_get_dma_addr’:
drivers/gpu/drm/exynos/exynos_drm_g2d.c:465:7: error: ‘vec’ undeclared (first use in this function)
  if (!vec)

Also, if g2d_userptr->vec is NULL it should assign -ENOMEM in ret. It
will fix below compile warning.

drivers/gpu/drm/exynos/exynos_drm_g2d.c: In function ‘exynos_g2d_set_cmdlist_ioctl’:
drivers/gpu/drm/exynos/exynos_drm_g2d.c:415:6: warning: ‘ret’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  int ret;
      ^
Signed-off-by: Joonyoung Shim <jy0922.shim@samsung.com>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>