Revert "iommu/ipmmu-vmsa: Drop LPAE Kconfig dependency"
This reverts commit bad78b13e3057b4bbfe769e21c213dca7c4d51de.

Stephen Rothwell reported this build error on linux-next with
x86_64 allmodconfig:

drivers/iommu/ipmmu-vmsa.c:24:27: fatal error: asm/dma-iommu.h: No such file or directory

Reverting this patch for now.

Signed-off-by: Joerg Roedel <jroedel@suse.de>