staging: board: Kconfig: Let STAGING_BOARD depend on CLKDEV_LOOKUP
It needs clk_add_alias() from clk drivers, which is implemented in
"drivers/clk/clkdev.c" which depends on CLKDEV_LOOKUP.

Normally, archs and clk driver its own will decide whether select
CLKDEV_LOOKUP, and common drivers will decide whether depend on it.

The related error (with allmodconfig under cris for next-20150702):

  drivers/built-in.o: In function `board_staging_register_clock':
  drivers/staging/board/board.c:131: undefined reference to `clk_add_alias'

Signed-off-by: Chen Gang <gang.chen.5i5j@gmail.com>