PCI: rcar: Build only on ARM
The pci-rcar-gen2.c and pcie-rcar.c drivers use struct pci_sys_data, which
only exists on ARM.  Building them on other arches, e.g., arm64/shmobile,
causes errors like this:

  drivers/pci/host/pci-rcar-gen2.c: In function 'rcar_pci_cfg_base': drivers/pci/host/pci-rcar-gen2.c:112:34: error: dereferencing pointer to incomplete type
    struct rcar_pci_priv *priv = sys->private_data;
                                    ^
Make these drivers depend on ARM unconditionally.

[bhelgaas: changelog]
Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>