drm/tilcdc: Fix build error
Fix error introduced by commit
c1e9c32b2832bb636a9a2164300f85056d36d679 during build when
CONFIG_DRM_TILCDC=y is selected:

drivers/gpu/drm/tilcdc/tilcdc_drv.c: In function ‘tilcdc_pm_suspend’:
drivers/gpu/drm/tilcdc/tilcdc_drv.c:546:36: error: ‘struct device’ has
no member named ‘dev’

Signed-off-by: Dave Gerlach <d-gerlach@ti.com>
Signed-off-by: Darren Etheridge <detheridge@ti.com>