thermal: rockchip: fix compile error
Missing a include file caused compile error.

drivers/thermal/rockchip_thermal.c:
In function 'rockchip_thermal_suspend':
drivers/thermal/rockchip_thermal.c:720:2: error: implicit
declaration of function 'pinctrl_pm_select_sleep_state'
[-Werror=implicit-function-declaration]
pinctrl_pm_select_sleep_state(dev);
                 ^
drivers/thermal/rockchip_thermal.c:
In function 'rockchip_thermal_resume':
drivers/thermal/rockchip_thermal.c:759:2: error: implicit
declaration of function 'pinctrl_pm_select_default_state'
[-Werror=implicit-function-declaration]
^pinctrl_pm_select_default_state(dev);
cc1: some warnings being treated as errors

Fixes: 7e38a5b1daa1 ("thermal: rockchip: support the sleep pinctrl state
to avoid glitches")

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Caesar Wang <wxt@rock-chips.com>
Signed-off-by: Eduardo Valentin <edubezval@gmail.com>