drm/bridge: ps8622 and ptn3460 depend on gpiolib
The ptn3460 driver recently started usign the gpiod interface
which is only available on platforms that come with GPIOLIB
support, resulting in a compile-time error:

drivers/gpu/drm/bridge/ps8622.c: In function 'ps8622_pre_enable':
drivers/gpu/drm/bridge/ps8622.c:368:2: error: implicit declaration of function 'gpiod_set_value' [-Werror=implicit-function-declaration]
  gpiod_set_value(ps8622->gpio_rst, 0);
  ^
drivers/gpu/drm/bridge/ps8622.c: In function 'ps8622_probe':
drivers/gpu/drm/bridge/ps8622.c:584:2: error: implicit declaration of function 'devm_gpiod_get' [-Werror=implicit-function-declaration]
  ps8622->gpio_slp = devm_gpiod_get(dev, "sleep");
  ^

Similarly, the newly added ps8622 driver started out with the same
problem.

This patch adds explicit Kconfig dependencies to avoid trying to
build invalid configurations.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: f1336e6afb ("drm/bridge: Add I2C based driver for ps8622/ps8625 bridge")
Fixes: af478d8823 ("drm/bridge: ptn3460: use gpiod interface")
Reviewed-by: Javier Martinez Canillas <javier.martinez@collabora.co.uk>
Signed-off-by: Thierry Reding <treding@nvidia.com>