list, perf: fix list_force_poison() build regression
    In file included from
    /home/sfr/next/next/tools/include/linux/list.h:5:0,
                     from arch/../util/map.h:6,
                     from arch/../util/event.h:8,
                     from arch/../util/debug.h:7,
                     from arch/common.c:4:
    include/linux/list.h: In function 'list_force_poison':
    include/linux/list.h:123:56: error: unused parameter 'entry' [-Werror=unused-parameter]
     static inline void list_force_poison(struct list_head *entry)

perf does not like the empty definition of list_force_poison.  For
simplicity just switch to list_del in the non-debug case.

Fixes "mm, dax, pmem: introduce {get|put}_dev_pagemap() for dax-gup" in
-next.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>