TI: media: chips-media: wave5: initialize variable
Initialize ret variable in two functions to fix build issue:
 wave5-helper.c:268:6: error: variable 'ret' is used uninitialized
 whenever 'if' condition is false [-Werror,-W sometimes-uninitialized]

Fixes: c08bc57d0e3e ("media: chips-media: wave5: Add Support for Frequency Points")
Change-Id: I9e05a019b1c15e679ac568a513f05ea34a8ce0d5
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>
(cherry picked from commit 2faf22c00003556294f53007c8d6bfb18ef4fb51)