ARM: EXYNOS: fix exynos randconfig build error
The following error was observed with SMP=n in v4.0-rc1:

arch/arm/mach-exynos/pm.c: In function 'exynos_cpu0_enter_aftr':
arch/arm/mach-exynos/pm.c:246:4: error: implicit declaration of function 'arch_send_wakeup_ipi_mask' [-Werror=implicit-function-declaration]

As the code unconditionally calls a function only available with SMP=y,
make the Exynos PM support depend on SMP.

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Kukjin Kim <kgene@kernel.org>