mm: fix build problems from lookup_page_ext
A patch for lookup_page_ext introduced several build errors and
warnings, e.g.

mm/page_owner.c: In function '__set_page_owner':
mm/page_owner.c:71:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
include/linux/page_idle.h: In function 'set_page_young':
include/linux/page_idle.h:62:3: error: expected ')' before 'return'

This fixes all of them. Please fold into the original patch.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 38c4fffbad3c ("mm: check the return value of lookup_page_ext for all call sites")