infiniband: rxe: avoid 64-bit division
The rxe driver fails to build on 32-bit because of a 64-bit division:

In function `rxe_qp_from_attr':
:(.text+0x53158): undefined reference to `__aeabi_uldivmod'

We can easily avoid this division by converting the nanosecond value
into jiffies directly rather than converting to microseconds first.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Leon Romanovsky <leon@kernel.org>