TI: drm/tidss: fix uninitialized variable
When we build with android build fail on :
 error: variable 'mask' is used uninitialized whenever 'if' condition is
 false

To fix this initialize mask variable.

Fixes: 93022077f0f5 ("TI: drm/tidss: Add OLDI bridge support")
Change-Id: Idb42061bf173831adf53de130f0817f93842e276
Signed-off-by: Guillaume La Roque <glaroque@baylibre.com>
Reviewed-by: Aradhya Bhatia <a-bhatia1@ti.com>
(cherry picked from commit d0d1c85c6a0265054fae482713a8d17d2c5839ef)