iommu/vt-d: Fix compile error when CONFIG_INTEL_IOMMU=n
The patches for the Intel IOMMU driver to fix issues with
kdump introduced a compile error with:

CONFIG_DMAR_TABLE=y
CONFIG_INTEL_IOMMU=n
CONFIG_IRQ_REMAP=y

The error manifests as:

drivers/iommu/intel_irq_remapping.c: In function ‘modify_irte’:
drivers/iommu/intel_irq_remapping.c:149:11: error: ‘struct
intel_iommu’ has no member named ‘pre_enabled_ir’
  if (iommu->pre_enabled_ir)

Fix this by moving the declaration of the pre_enabled_ir
under #ifdef CONFIG_IRQ_REMAPPING instead of
CONFIG_INTEL_IOMMU.

Reported-by: Jim Davis <jim.epost@gmail.com>
Cc: Zhen-Hua Li <zhen-hual@hp.com>
Signed-off-by: Joerg Roedel <jroedel@suse.de>