ANDROID: GKI: fix protected exports list
The protected export list needs to be updated after the patchset at
http://r.android.com/3549080 was merged. Otherwise, this triggers an
error when trying to update the STG file:

  ERROR: protected exports list must be updated before updating ABI definition.
      To update, execute
          tools/bazel run @@//common:kernel_aarch64_abi_update_protected_exports

Cc: Giuliano Procida <gprocida@google.com>
Fixes: b0279491475b ("ANDROID: GKI: Enable CONFIG_BT_HCIBTUSB_AUTO_ISOC_ALT")
Change-Id: Ib2014e78b2c0dc603990c9629e6b560c740cbc96
Signed-off-by: Carlos Llamas <cmllamas@google.com>